### ISSUE TITLE
Autoriser l'utilisateur à modifier le choix du serveur

### ISSUE THREAD

**Issue by Mizenos** [FlyzZx/LogoFinder#23]
Permettre la configuration du serveur sur lequel récupérer le fichier index.json et les fichiers vocabulary.yml et classifiers.xml.
Il faut ajouter une activité pour que l'utilisateur puisse entre les paramètres.

**Comment by FlyzZx** [comment]
A voir comment on pourrait faire, mais je pense qu'il va falloir se refaire une nuit complète en étant très efficace car on rentre dans un process de serveur / API avec possibilité de lancer un train à distance..
On en discute

**Comment by Mizenos** [comment]
J'ai ouvert cette issue pour le paramètrage de l'accés au serveur.
Pour l'ajustement du paramètrage SIFT je ne sais pas si cela vaut le coup de le faire à distance via l'appli car cela ne pourra fonctionner qu'avec notre serveur.

**Comment by FlyzZx** [comment]
Enregistre les parametres dans une BDD SQLite interne, si tu l'as jamais fait tu vas t'amuser 😃 
On en discute 💋

**Comment by FlyzZx** [comment]
Close with #28
