### ISSUE TITLE
Verifier la version des fichiers distants

### ISSUE THREAD

**Issue by FlyzZx** [FlyzZx/LogoFinder#25]
Il faut vérifier la version des fichiers côté serveur pour ne pas tout retelecharger systématiquement

**Comment by FlyzZx** [comment]
@Mizenos supprime le dossier si il faut les re DL ;)

**Comment by Mizenos** [comment]
Il faudrait que l'on s'arrête sur un système permettant de contrôler la version des fichiers.
Que ce soit une variable dans l'index ou un Datetime tout simple.

**Comment by FlyzZx** [comment]
Close with #27
